### ISSUE TITLE
effil.version is 0.1.0

### ISSUE THREAD

**Issue by adrfantini** [loud-hound/woofer#152] opened 2020-07-14 10:15 UTC
Hi, I installed `effil` using `luarocks install effil` on a new system. `luarocks` correclty installed version 1.1.0.
However:
```lua
> effil = require 'effil'
> effil.version
0.1.0
```
Why?

**Comment by mihacooper** [comment] 2020-07-14 10:29
That's known bug caused by hardcoded version in sources. I'll try to automate version update taking it from git tags.

Thanks for reminding.

**Comment by mihacooper** [comment] 2020-07-15 13:09
Fixed in version 1.1.1

**Closed as completed by mihacooper** 2020-07-15 13:09 UTC

**Comment by adrfantini** [comment] 2020-07-15 13:15
Thanks! Keep up the good work!

**Comment by adrfantini** [comment] 2021-01-14 07:54
Uhm, I installed Effil 1.2.0 from Luarocks and this bug reappeared? Maybe something weird with my system?
How can I check?

**Comment by mihacooper** [comment] 2021-01-14 21:51
No, seems like I forgot to update it, again.
We still didn't automate it =\
